<a href="https://colab.research.google.com/github/Tomaicho/PyTorch-for-Deep-Learning-Bootcamp/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#00. PyTorch Fundamentals

#Introduction to Tensors

###Creating tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1, 5],
                       [3, 1]])
MATRIX

tensor([[1, 5],
        [3, 1]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 1])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0, 1]

tensor([3, 6, 9])

In [ ]:
TENSOR[0,2, 0]

tensor(2)

###Random Tensors

In [ ]:
#Create a random Tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.dtype

(tensor([[0.8816, 0.0115, 0.2839, 0.6463],
         [0.8079, 0.8680, 0.3013, 0.1746],
         [0.1012, 0.4388, 0.8535, 0.1800]]),
 torch.float32)

In [ ]:
#Create a random tensor of size (224, 224, 3) - RGB image
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_tensor = torch.rand(size=(224, 224, 10))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 10]), 3)

###Zeros and ones

In [ ]:
#Tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Tensor of all ones
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

###Create a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_tensor = torch.arange(0, 21)
new_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [ ]:
new_tensor = torch.arange(0, 21, 2)
new_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros, ten_zeros.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64)

###Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults is None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type (cpu or cuda)
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
another_float16_tensor = torch.rand(size=(1,3), dtype=torch.float16)
another_float16_tensor

tensor([[0.2563, 0.3364, 0.3213]], dtype=torch.float16)

###Tensor Attributes

In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor is on device: {some_tensor.device}")

tensor([[0.9069, 0.3127, 0.2753, 0.8543],
        [0.9342, 0.2696, 0.5163, 0.5083],
        [0.7133, 0.7596, 0.6074, 0.2731]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Tensor is on device: cpu


###Manipulating tensor

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

Matrix multiplication

In [ ]:
#Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#Dot product
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
            [3,1],
            [2,1]])
tensor_B = torch.tensor([[2, 0],
            [1,3],
            [1,3]])

In [ ]:
torch.mm(tensor_A, tensor_B.T) #transpose of B in order to meet inner dimensions

tensor([[2, 7, 7],
        [6, 6, 6],
        [4, 5, 5]])

###Min, max, mean, sum

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Finding the tensor position of min and max of tensor

In [ ]:
 x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

###Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way






In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stackedv = torch.stack([x, x, x, x], dim = 0)
x_stackedv

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors horizontally
x_stackedh = torch.stack([x, x, x, x], dim = 1)
x_stackedh

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a tensor
x_reshaped = x.reshape(1, 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute() - rearranges the dimensions of a tensor in a specifies order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute to put colour channels first
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.2777, 0.5606, 0.9970],
         [0.0892, 0.8523, 0.5729],
         [0.1370, 0.2303, 0.8677],
         ...,
         [0.2599, 0.4129, 0.2727],
         [0.0286, 0.7921, 0.8717],
         [0.2216, 0.6631, 0.3634]],

        [[0.0458, 0.8225, 0.4537],
         [0.7541, 0.4720, 0.4722],
         [0.1253, 0.3104, 0.3991],
         ...,
         [0.8857, 0.6561, 0.4446],
         [0.9017, 0.3891, 0.4679],
         [0.2633, 0.5402, 0.2219]],

        [[0.9902, 0.0313, 0.5743],
         [0.0304, 0.3259, 0.5411],
         [0.7547, 0.7874, 0.6238],
         ...,
         [0.5334, 0.8518, 0.5785],
         [0.4456, 0.0942, 0.1494],
         [0.2308, 0.3671, 0.8428]],

        ...,

        [[0.7028, 0.6481, 0.7919],
         [0.1023, 0.0927, 0.9496],
         [0.9104, 0.4103, 0.4668],
         ...,
         [0.9344, 0.3912, 0.4861],
         [0.7272, 0.8610, 0.1251],
         [0.4230, 0.8637, 0.8008]],

        [[0.7190, 0.5611, 0.5004],
         [0.6127, 0.8095, 0.4291],
         [0.

In [ ]:
x_original[0, 0, 0] = 1.
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1.), tensor(1.))

###Indexing (selecting data from tensors)

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:, 0] # : selects all of the dimension, so returns list

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch and Numpy
NumPy -> PyTorch: torch.from_numpy(ndarray)

PyTorch -> NumPy: torch.Tensor.numpy()

In [ ]:
# NumPy to PyTorch tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting, tensor will keep same data type from numpy (float64)
array, array.dtype, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = tensor.type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Changing array doesn't change tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # numpy array keeps same datatype of tensor
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Changing tensor doesnt change numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (controlling randomness)
Use of seeds

In [ ]:
import torch

tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.7255, 0.4908, 0.8876, 0.5720],
        [0.1399, 0.7905, 0.5947, 0.5048],
        [0.6477, 0.3900, 0.2912, 0.8527]])
tensor([[0.8955, 0.3186, 0.9991, 0.6203],
        [0.5719, 0.8541, 0.1962, 0.7510],
        [0.3131, 0.7658, 0.1536, 0.0786]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # manual seed resets after creating a tensor. Need to redeclare
tensor_B = torch.rand(3,4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU

In [ ]:
!nvidia-smi

Mon Feb  5 16:36:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check GPU access
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

## Putting tensors (and models) in GPU

In [ ]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device) #cpu is default


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###Moving tensors back to cpu
Numpy only works in cpu

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu #remains unchanged

tensor([1, 2, 3], device='cuda:0')